apiVersion: v1
kind: Service
metadata:
    labels:
        service: backend-user
    name: backend-user
spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
        service: backend-user