apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      volumes:
        - name: configmap-volume
          configMap:
            name: env-config
      containers:
      - image: aisamuel/udagram-api-user:v1
        name: backend-user 
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"