apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      volumes:
        - name: configmap-volume
          configMap:
            name: env-config
      containers:
      - image: aisamuel/udagram-api-feed:v1
        name: backend-feed
        ports:
        - containerPort: 80 
        imagePullPolicy: Always  
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"                  