export const config = {
  // 'username': "samuelnewdb",
  // 'password': "Samuel991w#*@#",
  // 'database': "postgres",
  // 'host': "samuelnewdb.ckfqkerfv4gg.us-east-1.rds.amazonaws.com",
  // 'dialect': 'postgres',
  // 'aws_region': "us-east-1",
  // 'aws_profile': "default",
  // 'aws_media_bucket': "test-2345677-sam-dev",
  // 'url': "http://localhost:8100",
  // 'jwt': {
  //   'secret': "testing",
  // },
  'username': process.env.POSTGRES_USERNAME,
  'password': process.env.POSTGRES_PASSWORD,
  'database': process.env.POSTGRES_DB,
  'host': process.env.POSTGRES_HOST,
  'dialect': 'postgres',
  'aws_region': process.env.AWS_REGION,
  'aws_profile': process.env.AWS_PROFILE,
  'aws_media_bucket': process.env.AWS_BUCKET,
  'url': process.env.URL,
  'jwt': {
    'secret': process.env.JWT_SECRET,
  },
};
